name: rconfig
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.6
  flutter:
    sdk: flutter
  firebase_core: ^2.17.0
  firebase_remote_config: ^4.2.7
  firebase_analytics: ^10.5.1

dev_dependencies:
  flutter_lints: 2.0.3
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
