// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCupBDcAMf2CAOBltgnuA_b_g3klMr-QaY',
    appId: '1:201550128415:web:4189a0111e72deacfcbc2a',
    messagingSenderId: '201550128415',
    projectId: 'remoteconfigpocritic',
    authDomain: 'remoteconfigpocritic.firebaseapp.com',
    storageBucket: 'remoteconfigpocritic.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgXy6NeYzhmYt2Rwb1AMht6b7jM_QOS8M',
    appId: '1:201550128415:android:a4c60b13c3902136fcbc2a',
    messagingSenderId: '201550128415',
    projectId: 'remoteconfigpocritic',
    storageBucket: 'remoteconfigpocritic.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBoIsFhc0gBrQQ6U3eKVtv7Em0qgkYUN4',
    appId: '1:201550128415:ios:504fa80fe6cf75a7fcbc2a',
    messagingSenderId: '201550128415',
    projectId: 'remoteconfigpocritic',
    storageBucket: 'remoteconfigpocritic.appspot.com',
    iosBundleId: 'com.ritic.rconfig.rconfig',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBoIsFhc0gBrQQ6U3eKVtv7Em0qgkYUN4',
    appId: '1:201550128415:ios:dc27214040650ea9fcbc2a',
    messagingSenderId: '201550128415',
    projectId: 'remoteconfigpocritic',
    storageBucket: 'remoteconfigpocritic.appspot.com',
    iosBundleId: 'com.ritic.rconfig.rconfig.RunnerTests',
  );
}
